apiVersion: v1
kind: Service
metadata:
  name: ViperMonkey-rest
  labels:
    app: ViperMonkey
spec:
  type: NodePort
  selector:
    app: ViperMonkey
  ports:
  - port: 8080
    protocol: TCP
    name: rest
    cohesityTag: ui
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ViperMonkey
  labels:
    app: ViperMonkey
spec:
  replicas:
    fixed: 1
  selector:
    matchLabels:
      app: ViperMonkey
  template:
    metadata:
      labels:
        app: ViperMonkey
    spec:
      containers:
      - name: ViperMonkey
        image: ViperMonkey:latest
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
